version: '3.9'

services:

    api:
        build: .
        image: inference-api
        ports:
            - 8883:8883
        volumes:
            - ./app:/app
        restart: unless-stopped
        stdin_open: true
        tty: true