version: '3.9'

services:

    api:
        build: .
        image: inference-api
        ports:
            - 80:80
        volumes:
            - ./app:/app
        restart: unless-stopped
        stdin_open: true
        tty: true